# [dein.toml]
[[plugins]]
repo = 'Shougo/dein.vim'

# coc
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
source ~/.config/nvim/plugins/coc.vim
'''

# ファイルツリーを表示
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add='''
nnoremap <silent> <Leader>e :NERDTreeToggle<CR>
'''

# git差分表示
[[plugins]]
repo = 'airblade/vim-gitgutter'
hool_add='''
set signcolumn=yes
set updatetime=100
'''

# debugger
[[plugins]]
repo = 'mfussenegger/nvim-dap'
depends = 'nvim-dap-ui'
hook_source = '''
lua << EOF
EOF
'''

[[plugins]]
repo = 'rcarriga/nvim-dap-ui'
on_source = 'nvim-dap'
hook_source = '''
lua << EOF
require("dapui").setup({
  icons = { expanded = "∨", collapsed = ">" },
  layouts = {
    {
      elements = {
        { id = "watches", size = 0.20 },
        { id = "stacks", size = 0.20 },
        { id = "breakpoints", size = 0.20 },
        { id = "scopes", size = 0.40 },
      },
      size = 64,
      position = "right",
    },
    {
      elements = {
        "repl",
        "console",
      },
      size = 0.20,
      position = "bottom",
    },
  },
})
EOF
'''

# mason
[[plugins]]
repo = 'williamboman/mason.nvim'
hook_add='''
lua << EOF
  require("mason").setup()
EOF
'''

# vin airlines
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

