# [dein.toml]
[[plugins]]
repo = 'Shougo/dein.vim'

# coc
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
source ~/.config/nvim/plugins/coc.vim
'''

# ファイルツリーを表示
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
source ~/.config/nvim/plugins/nerdtree.vim
'''

# git差分表示
[[plugins]]
repo = 'airblade/vim-gitgutter'
hool_add='''
source ~/.config/nvim/plugins/vim-gitgutter.vim
'''

# debugger
[[plugins]]
repo = 'mfussenegger/nvim-dap'
depends = 'nvim-dap-ui'

[[plugins]]
repo = 'rcarriga/nvim-dap-ui'
on_source = 'nvim-dap'
hook_add = '''
source ~/.config/nvim/plugins/nvim-dap-ui.vim
'''

# mason
[[plugins]]
repo = 'williamboman/mason.nvim'
hook_add='''
source ~/.config/nvim/plugins/mason.vim
'''

# jetbrains theme
[[plugins]]
repo = 'doums/darcula'
hook_add = '''
source ~/.config/nvim/plugins/darcula.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline#extensions#tabline#enabled = 1
'''
